# Generated by Django 4.2.18 on 2025-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_professionalprofile_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='job_type',
            field=models.CharField(choices=[('public', 'Δημόσιος Υπάλληλος'), ('private', 'Ιδιωτικός Υπάλληλος'), ('freelancer', 'Ελεύθερος Επαγγελματίας')], max_length=50),
        ),
    ]
